# Generated by Django 6.0 on 2026-05-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_teamassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamassignment',
            name='team',
            field=models.CharField(choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1),
        ),
    ]
