# Generated by Django 6.0 on 2026-05-06 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_teamassignment_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a_score', models.PositiveIntegerField(default=0)),
                ('team_b_score', models.PositiveIntegerField(default=0)),
                ('team_a_possession', models.PositiveIntegerField(default=50)),
                ('team_b_possession', models.PositiveIntegerField(default=50)),
                ('team_a_shots', models.PositiveIntegerField(default=0)),
                ('team_b_shots', models.PositiveIntegerField(default=0)),
                ('team_a_chances', models.PositiveIntegerField(default=0)),
                ('team_b_chances', models.PositiveIntegerField(default=0)),
                ('team_a_pass_accuracy', models.PositiveIntegerField(default=0)),
                ('team_b_pass_accuracy', models.PositiveIntegerField(default=0)),
                ('team_a_tackles', models.PositiveIntegerField(default=0)),
                ('team_b_tackles', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp_results', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='scheduling.matchsession')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='scheduling.matchsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'user')},
            },
        ),
    ]
